version: '3'

services:
  db:
    image: postgres:15
    container_name: auth-db
    restart: always
    ports:
      - '5555:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth

  api:
    build: .
    container_name: auth-api
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      PORT: 5000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/auth
      JWT_SECRET: secret
      JWT_EXPIRES_IN: 1d